### ISSUE TITLE
Create a .devcontainer folder

### ISSUE THREAD

**Issue by rosa-r-ma** [PromotionsSquad/promotions#24]
**As a** team 
 **I need** .devcontainer folder with the appropriate files  
 **So that** members of the team can quickly get a development environment running  
   
 ### Details and Assumptions
The Dockerfile in the devcontainer folder should install all of the needed software to run the service
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a team member opens Visual Code Studio
When the team member reopens in the container
Then the team member is able to start developing

**Comment by devopstudent** [comment]
@tv547 This Issue needs a Pull Request in order to be considered in **Review/QA**. Where is the Pull Request for this work?

**Comment by rofrano** [comment]
@tv547 This Issue needs a Pull Request in order to be considered in **Review/QA**. Where is the Pull Request for this work?

**Comment by tv547** [comment]
@rofrano know we discussed this offline after class last night, but apologies again. In the future will do a pull request so that proper QA can be performed.

**Comment by rofrano** [comment]
@tv547 No worries. It's all part of the learning experience. :-)

**Comment by tv547** [comment]
Correct as part of refactoring tdd
