### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by kripa528** [PromotionsSquad/promotions#26]
**As a** Marketing Manager
 **I need** to create a .gitignore file  
 **So that** I can control what files are uploaded to the master repository  
   
 ### Details and Assumptions
-I know how to create a .gitignore file
-I know what files I want to track

   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I create a .gitignore file
 When I work to upload files to the master repository
 Then I can track the files I don't want uploaded to the master repository

**Comment by rosa-r-ma** [comment]
This is already in the Promotions repo (copied over from John's project-template repo). There, I don't think we need to do this and can tag this issue as 'won't fix'

**Comment by tv547** [comment]
Brought over with refactor tdd pull request. Reassigned
