### ISSUE TITLE
Create routes.py file

### ISSUE THREAD

**Issue by mahfujhussain** [PromotionsSquad/promotions#27]
**As a** development team
 **We need** a routes.py file
 **So that** flask service routes can be contained
   
 ### Details and Assumptions
 * A routes.py file is needed so that a URL can be mapped directly to code/application actions
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I am a developer
 When I create a routes.py file
 Then code/application actions are properly mapped

**Comment by tv547** [comment]
Brought over with cloning on John's lab_flask_tdd file so marking as won't fix
