### ISSUE TITLE
Publish Promotion

### ISSUE THREAD

**Issue by mahfujhussain** [PromotionsSquad/promotions#7]
**As a** Marketing Manager  
 **I need** the ability to publish our promotion  
 **So that** customers can claim it 
   
 ### Details and Assumptions
 * The promotion has been approved 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the promotion is finalized
 When the promotion is approved
 Then the promotion is published
```gherkin

**Comment by rosa-r-ma** [comment]
Closing this as we're no longer pursuing it.
